### ISSUE TITLE
New CW340 board is non-functional

### ISSUE THREAD

**Issue by AndySecqai** [newaetech/cw340-luna-board#3]
We have fresh-out-of-the-box CW340 card that appears to be non-functional and require some assistance with debugging.

Once connected to the host computer, we can successfully run the OpenTitan [set-pll](https://opentitan.org/book/doc/getting_started/setup_fpga.html#detecting-the-board) command, which I think indicates that USB communications are working to the SAM3X, and I2C communications are working from the SAM3X to the PLL.

`dmesg -Hw` is not showing any errors, and `lsusb` appears to be detecting things as I would expect:
```
Bus 003 Device 004: ID 0403:6011 Future Technology Devices International, Ltd FT4232H Quad HS USB-UART/FIFO IC
Bus 003 Device 005: ID 2b3e:c340 NewAE Technology Inc. ChipWhisperer CW340 - Luna Board
Bus 003 Device 002: ID 0424:2534 Microchip Technology, Inc. (formerly SMSC)
```

However, from this point, nothing seems to be able to communicate correctly:
- the Vivado Hardware Manager reports that there are no connected devices
- the opentitantool (when set to [program the bitstream](https://opentitan.org/book/doc/getting_started/setup_fpga.html#manually-loading-a-bitstream-onto-the-fpga-with-opentitantool)) returns `Error: Transport does not support Uart` (which I think means it can't detect the right JTAG connection?)
- trying to update the SAM3X firmware following [this](https://rtfm.newae.com/Targets/CW340%20Luna%20Board/#step-1-erasing-the-sam3x) guide also fails with the following:
```
target = cw.target(None, cw.targets.CW310)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<removed>/python3.10/site-packages/chipwhisperer/__init__.py", line 7, in target
    rtn.con(scope, **kwargs)
  File <removed>/python3.10/site-packages/chipwhisperer/capture/targets/_base.py", line 65, in con
    self._con(scope, **kwargs)
  File <removed>/python3.10/site-packages/chipwhisperer/capture/targets/CW310.py", line 122, in _con
    self._naeusb.con(idProduct=[0xC310], serial_number=sn, hw_location=hw_location)
  File "<removed>/python3.10/site-packages/chipwhisperer/hardware/naeusb/naeusb.py", line 681, in con
    self.usbtx.open(idProduct=idProduct, serial_number=serial_number, connect_to_first=True, hw_location=hw_location)
  File "<removed>/python3.10/site-packages/chipwhisperer/hardware/naeusb/naeusb.py", line 371, in open
    self.device = self.find(serial_number, idProduct, hw_location=hw_location)
  File "<removed>/python3.10/site-packages/chipwhisperer/hardware/naeusb/naeusb.py", line 338, in find
    raise OSError("Could not find ChipWhisperer. Is it connected?")
OSError: Could not find ChipWhisperer. Is it connected?
```

At this point, it looks to me like there is something wrong with the FTDI-to-FPGA connection, and/or the FPGA itself is dead (particularly due to the Vivado Hardware Manager not being able to see it), but hopefully someone has an idea of some other tests to try before I RMA it back to the distributer...

Thanks,
Andy

**Comment by jpcrypt** [comment]
How are you powering the board, what are the positions of all the power delivery switches, and what LEDs are on or blinking?

**Comment by AndySecqai** [comment]
Please see attached for a picture of the board configuration with the various leds showing:
![signal-2024-04-25-141837](https://github.com/newaetech/cw340-luna-board/assets/156907195/1a0abab7-ef4b-4971-a1ac-1b5f9d5dc413)

We are mostly following the OpenTitan getting started guide [here](https://opentitan.org/book/doc/getting_started/setup_fpga.html#cw340-board), however we have SW7 to the left as the board seems unpowered with it to the right as stated in that guide.

If it is possible to tell from the attached pictures, do our jumpers look correctly configured? They've been left as-was from taking it out of the box...

**Comment by AndySecqai** [comment]
Hi @colinoflynn - I just took a quick look at the test note book you linked to, but it seems like maybe something isn't right in my python environment:
```
<user>:~/cw340-luna-board/fpga/vivado/cw341.runs/impl_1$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chipwhisperer as cw
>>> bsfile = 'cw341_top.bit'
>>> target = cw.target(None, cw.targets.CW340, bsfile=bsfile, force=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'chipwhisperer.capture.targets.CW310' has no attribute 'CW340'. Did you mean: 'CW310'?
```

**Comment by jpcrypt** [comment]
Can you update your ChipWhisperer installation to the develop branch?
It should then work.
Then you can try the test notebook [here](https://github.com/newaetech/cw340-luna-board/blob/main/jupyter/CW340_test.ipynb) to do basic validation.
You should see blinking blue and red LEDs to indicate that clocks are alive. A single additional jumper is required to run the tests, as explained in the notebook.

**Comment by AndySecqai** [comment]
@jpcrypt sorry - probably a dumb question on my part, but I'm not much of a python user - how would I change the installation to the develop branch? I just installed it with `pip3 install chipwhisperer`

**Comment by AndySecqai** [comment]
Sorry - ignore the above, I found the install instructions in the chipwhisperer repo. I'm pretty sure I got the the `develop` branch set up correctly, but the Python instructions still don't seem right:

```
:~/cw340-luna-board/fpga/vivado/cw341.runs/impl_1$ python
3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chipwhisperer as cw
>>> bsfile='cw341_top.bit'
>>> target = cw.target(None, cw.targets.CW340, bsfile=bsfile, force=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'chipwhisperer' has no attribute 'target'
>>>
```
